In [1]:
import pandas as pd

df = pd.read_csv('result.csv')
df

,value,confidence,x1,y1,x2,y2,x3,y3,x4,y4
0,ABC,0.995208,0.345171,0.166016,0.421888,0.166016,0.421888,0.185547,0.345171,0.185547
1,Park,0.999687,0.453970,0.166992,0.548820,0.166992,0.548820,0.183594,0.453970,0.183594
2,LTD,0.999580,0.582296,0.166016,0.656224,0.166016,0.656224,0.185547,0.582296,0.185547
3,Address,0.999324,0.385622,0.203125,0.559979,0.203125,0.559979,0.221680,0.385622,0.221680
4,1,0.999999,0.593455,0.199219,0.618563,0.199219,0.618563,0.224609,0.593455,0.224609
5,Address,0.986677,0.385622,0.239258,0.559979,0.239258,0.559979,0.257812,0.385622,0.257812
6,2,0.999995,0.594850,0.237305,0.615773,0.237305,0.615773,0.259766,0.594850,0.259766
7,PARKING,0.678185,0.310299,0.358398,0.484657,0.358398,0.484657,0.374023,0.310299,0.374023
8,RECEIPT,0.923008,0.518133,0.358398,0.692490,0.358398,0.692490,0.374023,0.518133,0.374023
9,CAR,0.999957,0.057830,0.552734,0.134548,0.552734,0.134548,0.572266,0.057830,0.572266
10,PARK:,0.999893,0.166629,0.554688,0.279613,0.554688,0.279613,0.570312,0.166629,0.570312
11,DATE:,0.996985,0.059225,0.594727,0.174998,0.594727,0.174998,0.611328,0.059225,0.611328
12,FROM:,0.981990,0.062015,0.634766,0.174998,0.634766,0.174998,0.650391,0.062015,0.650391
13,TO:,0.999563,0.057830,0.670898,0.126178,0.670898,0.126178,0.690430,0.057830,0.690430
14,CAR,0.999964,0.659014,0.552734,0.735731,0.552734,0.735731,0.572266,0.659014,0.572266
15,PARKING,0.994547,0.767812,0.554688,0.940775,0.554688,0.940775,0.570312,0.767812,0.570312
16,10:07:00,0.620955,0.665988,0.594727,0.858478,0.594727,0.858478,0.610352,0.665988,0.610352
17,AM,0.999788,0.893350,0.591797,0.947749,0.591797,0.947749,0.612305,0.893350,0.612305
18,09:06:44,0.998953,0.664593,0.632812,0.858478,0.632812,0.858478,0.651367,0.664593,0.651367
19,AM,0.997092,0.891955,0.631836,0.947749,0.631836,0.947749,0.652344,0.891955,0.652344
20,10:06:44,0.994763,0.664593,0.672852,0.858478,0.672852,0.858478,0.691406,0.664593,0.691406
21,AM,0.999773,0.893350,0.671875,0.947749,0.671875,0.947749,0.692383,0.893350,0.692383
22,3/15/12,0.646982,0.452372,0.591926,0.623751,0.589704,0.624346,0.612175,0.452966,0.614397
23,3/15/12,0.569437,0.455365,0.632812,0.622747,0.632812,0.622747,0.652344,0.455365,0.652344
24,3/15/12,0.686314,0.452966,0.669782,0.624346,0.672004,0.623751,0.694476,0.452372,0.692254
25,PAID,0.994636,0.060620,0.753906,0.158260,0.753906,0.158260,0.770508,0.060620,0.770508
26,V.A.T,0.998630,0.057830,0.792969,0.186157,0.792969,0.186157,0.811523,0.057830,0.811523
27,5.00,0.999881,0.844530,0.751953,0.939380,0.751953,0.939380,0.772461,0.844530,0.772461
28,0.50,0.999320,0.844530,0.791992,0.937985,0.791992,0.937985,0.811523,0.844530,0.811523

In [3]:
bad = df[df['confidence'] < 0.8]
bad

,value,confidence,x1,y1,x2,y2,x3,y3,x4,y4
7,PARKING,0.678185,0.310299,0.358398,0.484657,0.358398,0.484657,0.374023,0.310299,0.374023
16,10:07:00,0.620955,0.665988,0.594727,0.858478,0.594727,0.858478,0.610352,0.665988,0.610352
22,3/15/12,0.646982,0.452372,0.591926,0.623751,0.589704,0.624346,0.612175,0.452966,0.614397
23,3/15/12,0.569437,0.455365,0.632812,0.622747,0.632812,0.622747,0.652344,0.455365,0.652344
24,3/15/12,0.686314,0.452966,0.669782,0.624346,0.672004,0.623751,0.694476,0.452372,0.692254